---
- name: Remove derpsie service and script
  hosts: all 
  become: true
  gather_facts: true
  tasks:

  - name: Debug - ansible_distribution
    debug: var=ansible_distribution verbosity=2

  - name: Fail if not on Ubuntu
    assert: { that: "ansible_distribution == 'Ubuntu'" }

  - name: Disable and stop derpsie service
    service:
      name: derpsie
      state: stopped
      enabled: no

  - name: Remove upstart file for derpsie service and remove derpsie script
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - /etc/init/derpsie.conf
      - /usr/local/bin/derpsie
