---
- name: Set permissions for gunicorn log directory
  file:
    path: /var/log/gunicorn
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Set permissions for gunicorn log files
  file:
    path: "{{ item }}"
    state: touch
    owner: nobody
    group: nogroup
    mode: 0644
  with_items:
    - /var/log/gunicorn/access.log
    - /var/log/gunicorn/gunicorn.log

- name: Add gunicorn upstart configuration from template
  template:
    src: gunicorn.conf.j2
    dest: /etc/init/gunicorn.conf
    owner: root
    mode: 0644
  notify: Restart Gunicorn

- name: Enable gunicorn service and ensure it is running
  service:
    name: gunicorn
    state: started
    enabled: yes

